### ISSUE TITLE
 [Android Bootcamp] Project 1 - Review my app [ToDoList_Project]

### ISSUE THREAD

**Issue by TienVNguyen** [TienVNguyen/ToDoList_Project#1]
My app [ToDoList_Project] is completed. Please help to review and accept it!
/cc @coderschoolreview

Thanks & Best Regards,
Tien Nguyen

**Comment by coderschoolreview** [comment]
### Thank you for your Android submission, TienVNguyen!

 :ice_cream: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by TienVNguyen** [comment]
Thanks for your quick confirmation. I hope to receive a nice response from CoderSchool.vn as soon as possible. Cheer! :+1: 

Thanks & Best Regards,
Tien Nguyen

**Comment by hoanle** [comment]
hi @TienVNguyen 

Thanks for the submission

In general
- The app runs nicely
- Nice animation on ListView & Author session
- It's nice that you created your own adapter, used SQLiteDatabase & used include tag in layout file
- Clear structure of module, package

Detail & Suggestion
- There are a lot of comments. Comments are good but too many can make it harder to catch 
- You can try to use DialogFragment for EditItem & Author session. Create a AuthorDialogFragment, show it with animation whenever you want. This way, the author session can be reused at several places, not only the main screen. DialogFragment is a good practice
- Instead of using several different ImageView, you might want to use something like Drawable Selector, or LevelListDrawable

**Comment by TienVNguyen** [comment]
Hi @hoanle,

I am appreciate your reply. And it is a very good resource for me to improve mine. By the way, I also have my reply to yours:
1/ For lots of comments, it may become my habit after some projects with Japanese customers. I will try to cover many comments into one for better catch.
2/ For DialogFragment, I will start to study it now. So, maybe one or two more day, I will update the ToDoList project.
3/ For Drawable Selector, I face an issue with it. Please correct me if I'm wrong. Because it's completely new to me, I guess Drawable Selector is not supported good at API 16, is it!
Example:
- [**remove_icon.xml**] in res\drawable
- [**header_menu_layout.xml**] in res\layout - **line 18 => 23**
- [**MainActivity.java**] in java source - **line 275 => 290**

[Drawable_Selector.zip](https://github.com/TienVNguyen/ToDoList_Project/files/149409/Drawable_Selector.zip)

==> I can set the Background (item with src:icon) to button. But it's failed due to comparison between two Drawable. So, I would like to hear for your suggestion on this.

Thanks & Best Regards,
Tien Nguyen

**Comment by hoanle** [comment]
@TienVNguyen 

Hi

1 - You can't simple compare two Drawable that way. You only can compare two Bitmaps. However, There are some ways to do it. For example, using Drawable constant state 

Like this
`
removeIconObject.getBackground().getConstantState().equals(ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_cancel_white_24dp).getConstantState()
`
A good read on constant state of Drawable.

About the issue, my idea is to create a custom state of the button. For example, the button now has several different, custom states like "EDITING_MODE", "REMOVING_MODE". How to create custom states. You can [read](http://ptrprograms.blogspot.com/2015/01/implementing-and-using-custom-drawable.html)

2 -  It's easier if you use LevelListDrawable. It's very popular, the Wifi icon at the top bar of every android device is usually LevelListDrawable

```
 <level-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:maxLevel="0" android:drawable="@drawable/ic_wifi_signal_1" />
  <item android:maxLevel="1" android:drawable="@drawable/ic_wifi_signal_2" />
  <item android:maxLevel="2" android:drawable="@drawable/ic_wifi_signal_3" />
  <item android:maxLevel="3" android:drawable="@drawable/ic_wifi_signal_4" />
 </level-list>
```

**Comment by TienVNguyen** [comment]
Hi @hoanle,

1/ LevelListDrawable is great. I just applied it. Great suggestion. :+1: 
2/ DialogFragment is in progress at the moment.

Thanks & Best Regards,
Tien Nguyen

**Comment by TienVNguyen** [comment]
Hi @hoanle,

I'm sorry for the delay. The DialogFragment costed me three days (around 2h/day) to apply it successfully. 
However, the effect is so cool. Unbelievable!. Nice suggestion :+1: 

**P/s:** I just applied it successfully. So the code may look nasty at the moment. I'll update later.
Thanks & Best Regards,
Tien Nguyen
